# Site settings
title: Álvaro León - Data Scientist
description: Portafolio/Blog personal de proyectos de data science
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Álvaro León
user_description: Soy sociólogo, con estudios previos de ingeniería, y máster en Big Data y Data Science. Tengo experiencia en equipos multidisciplinarios centrados en el análisis de datos para diagnósticos, generación de conocimiento y toma de decisiones. Me motivan los desafíos profesionales que me permiten desarrollar constantemente mis habilidades. Soy proactivo, resolutivo y autodidacta. Además, trabajo muy bien en equipos cumpliendo distintas funciones, en escenarios cambiantes y bajo presión.
user_title: Data Scientist
email: alvaroleongarrido@gmail.com
twitter_username: AlvaroLayon
github_username:  alvaroleongarrido
gplus_username:  None

# Google-analytics
google-analytics:
  id: "UA-162677242-1"

exclude: ['package.json', 'src' , 'node_modules']
